name: build & test

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build example code
        run: gcc -o mintest_example mintest_example.c
      - name: Test example code
        run: sh mintest_example_test.sh
